---
- name: "add Node.js from Nodesource"
  become: yes
  shell:
    curl -sh https://deb.nodesource.com/setup_13.x | sudo -E bash -

- name: "install Node.js 13"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "install PM Globally"
  become: yes
  npm:
    name: pm2
    global: yes

    