---
- name: "creates directory backend-app"
  file:
    path: ~/backend-app
    state: directory

- name: "node dependencies install"
  shell: |
    cd ~/backend-app
    npm install

- name: "start pm2 after configure"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu